### PR TITLE
New version: Microbiome v0.6.0

### PR DESCRIPTION
**Pull request by BioJuliaBot**
- Registering package: Microbiome
- Repository: https://github.com/BioJulia/Microbiome.jl
- Created by: @kescobo
- Version: v0.6.0
- Commit: 87d887aabb277b41a08ad83770a971f911af86fd
- Reviewed by: @kescobo
- Reference: https://github.com/BioJulia/Microbiome.jl/issues/39#issuecomment-573237549

### CODE REVIEW

**Comment by TransGirlCodes** [comment]
@DilumAluthge The AutoMerge does not seem able to install the package, due to not finding dependencies (specifically Distances) which are available in General. Is there some other part of the AutoMerge process where dependency registries need to be added? Perhaps around here https://github.com/JuliaRegistries/RegistryCI.jl/blob/f0350a8667cc7d27d8f369df9790fa171032ee3e/src/AutoMerge/guidelines.jl#L202 ?

**Comment by TransGirlCodes** [comment]
@kescobo CI Travis looks like everything is fine for this. I think it's just the AutoMerge bot isn't yet fully updated to allow registry dependencies. I must have missed something from my PR.

**Comment by kescobo** [comment]
@BenJWard Thanks for looking into that. I'm done for the day - I can leave this open for now if that would be helpful, but will merge when I need it 👍

**Comment by DilumAluthge** [comment]
@BenJWard Can you open an issue on RegistryCI to remind me? It shouldn’t be too difficult.

**Comment by kescobo** [comment]
@DilumAluthge Just made the issue - is it helpful to leave this PR open for you to debug, or can I merge it?

**Comment by DilumAluthge** [comment]
> @DilumAluthge Just made the issue - is it helpful to leave this PR open for you to debug, or can I merge it?

If possible, it would be great if you could leave it open for me to debug.

**Comment by kescobo** [comment]
@DilumAluthge Sure thing - I'll need it for work next week, but worst case I can release 0.6.1 which presumably would have the same problems.

**Pull request merged**
