### PR TITLE
New package: BBI v0.1.1

### PR DESCRIPTION
**Pull request by BioJuliaBot**
- Registering package: BBI
- Repository: https://github.com/BioJulia/BBI.jl
- Created by: @CiaranOMara
- Version: v0.1.1
- Commit: 4b1d3d9d108d28b7d14098bbe04e7b77b1d51081
- Reviewed by: @CiaranOMara
- Reference: https://github.com/BioJulia/BBI.jl/commit/4b1d3d9d108d28b7d14098bbe04e7b77b1d51081#commitcomment-37396744

### CODE REVIEW

**Comment by CiaranOMara** [comment]
Don't merge this one.

**Comment by TransGirlCodes** [comment]
@CiaranOMara If this one does not get released, then it makes no sense to make the next release 0.2 according to semver - since this 0.1 never got released. It's neater to make your changes and fixes and simply do a 0.1 release.

**Comment by CiaranOMara** [comment]
@BenJWard, unfortunately v0.1 was released via the general repository in early 2019.

**Comment by TransGirlCodes** [comment]
Ok I didn't know there was a 0.1 in general.

**Pull request closed without merging**
