### PR TITLE
Temporary: use a custom branch of RegistryCI.jl

### PR DESCRIPTION
**Pull request by DilumAluthge**
This will allow us to test https://github.com/JuliaRegistries/RegistryCI.jl/pull/202

cc: @BenJWard @kescobo

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@BenJWard Can you make a new registration? Let’s see if AutoMerge is working now.

**Comment by TransGirlCodes** [comment]
@DilumAluthge Nice it looks like it worked for #33! Thanks for taking the trouble to implement this!

**Comment by DilumAluthge** [comment]
Well... let’s wait until it’s actually merged before we celebrate :)

**Comment by DilumAluthge** [comment]
Alright looks like it was automerged

**Pull request merged**
