### PR TITLE
New package: GenomicAnnotations v0.1.3

### PR DESCRIPTION
**Pull request by BioJuliaBot**
- Registering package: GenomicAnnotations
- Repository: https://github.com/kdyrhage/GenomicAnnotations.jl
- Created by: @kdyrhage
- Version: v0.1.3
- Commit: 5a19426e56b4836444e365b6164798f826ad7619
- Reviewed by: @kdyrhage
- Reference: https://github.com/kdyrhage/GenomicAnnotations.jl/commit/5a19426e56b4836444e365b6164798f826ad7619#commitcomment-35233482

### CODE REVIEW

**Comment by TransGirlCodes** [comment]
I'm going to close this as 0.1.4 is available on General and this is for 0.1.3. If you want to register GenomicAnnotations here, please do so from the next released version so as it's not confusing for anyone looking to install a particular version.

**Comment by TransGirlCodes** [comment]
I'm reopening for the purposes of testing #29

**Comment by TransGirlCodes** [comment]
Ok I'm satisfied the AutoMerge is running correctly. I will close this again now.

**Comment by kdyrhage** [comment]
> I'm going to close this as 0.1.4 is available on General and this is for 0.1.3. If you want to register GenomicAnnotations here, please do so from the next released version so as it's not confusing for anyone looking to install a particular version.

Will do.

**Pull request closed without merging**
