### PR TITLE
New package: GenomicVectors v1.0.0

### PR DESCRIPTION
**Pull request by BioJuliaBot**
- Registering package: GenomicVectors
- Repository: https://github.com/phaverty/GenomicVectors.jl
- Created by: @phaverty
- Version: v1.0.0
- Commit: a61d67ce2d5765304a24c1abb41dfa06e2438237
- Reviewed by: @phaverty
- Reference: https://github.com/phaverty/GenomicVectors.jl/commit/a61d67ce2d5765304a24c1abb41dfa06e2438237#commitcomment-38204191

### CODE REVIEW

**Comment by phaverty** [comment]
Good morning, I'd like to register GenomicVectors.jl here from the General registry. I hope you like it. I had to bump the version from 0.5.0 to 1.0.0 to make the new package checks happy. I suppose 1.0.0 is OK.

**Comment by kescobo** [comment]
Great! I think this is a good place for it. Can you add links/badges for docs and a note about the need to install the BioJulia Registry to the README? [Take a look here](https://github.com/BioJulia/BioSequences.jl) for an example.

**Comment by phaverty** [comment]
I've added badges for docs and also the Installation section based on
BioSequences. Should I add the Testing or Contributing parts too?

**Comment by phaverty** [comment]
Also, do you just leave the old versions on the General registry?

**Comment by kescobo** [comment]
>I've added badges for docs and also the Installation section based on
BioSequences. 

Are they still on a branch? Latest commit on master is 22 days AFAICT

>Should I add the Testing or Contributing parts too?

If you like, but not necessary. Since the repo is not actually hosted in the BioJulia org (I think it would probably be accepted if you want, but no need for it), I don't think you need to follow all of the same guidelines. 

>Also, do you just leave the old versions on the General registry?

Yup - as long as the versions don't overlap, it should be fine. That said, if there are compat conflicts, it can cause issues at the moment (see eg #53). Probably not worth worrying about unless a problem arises, as I think the Pkg devs are working on a fix.

**Comment by phaverty** [comment]
Good morning,

Yes, this was still on a branch. I merged the updates to master just now.
Hosting under BioJulia org is interesting. Let me think about that a bit.

**Comment by kescobo** [comment]
>Hosting under BioJulia org is interesting. Let me think about that a bit.

Totally up to you, and no rush :-).

Last thing - if you'd like this version to point to the most recent commit that includes the README changes, you can comment [on the commit](https://github.com/phaverty/GenomicVectors.jl/commit/a61d67ce2d5765304a24c1abb41dfa06e2438237) asking BioJuliaBot to register again, and it will update this PR. If not, no worries, I'm happy to merge this as-is

**Comment by phaverty** [comment]
I've commented to activate the BioJuila registry bot on that commit just
now. Thanks for reminding me.

**Review by kescobo — APPROVED** [review]

**Comment by kescobo** [comment]
Awesome, thanks!

**Pull request merged**
